version: '3.7'
services:
  nest-api:
    container_name: user-management-nest-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - '8888:8888'
    depends_on:
      - postgres
    volumes:
      - .:/app

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5435:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
